### ISSUE TITLE
getConfig 空指针。

### ISSUE THREAD

**Issue by Mcayear** [Mcayear/LittleMonster#2]
```
22:53:53 [ERROR] [LittleMonster] BasePluginThreadTask Error
java.lang.NullPointerException: Cannot invoke "com.smallaswater.littlemonster.config.MonsterConfig.getName()" because the return value of "com.smallaswater.littlemonster.entity.IEntity.getConfig()" is null
        at com.smallaswater.littlemonster.utils.Utils.getMonster(Utils.java:237) ~[LittleMonster_v1.7.1-SNAPSHOT.jar:?]
        at com.smallaswater.littlemonster.utils.Utils.getEntityCount(Utils.java:209) ~[LittleMonster_v1.7.1-SNAPSHOT.jar:?]
        at com.smallaswater.littlemonster.threads.runnables.FlotTask.scheduler(FlotTask.java:47) ~[LittleMonster_v1.7.1-SNAPSHOT.jar:?]
        at com.smallaswater.littlemonster.threads.runnables.BasePluginThreadTask.run(BasePluginThreadTask.java:27) [LittleMonster_v1.7.1-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Mcayear** [comment]
https://github.com/Mcayear/LittleMonster/commit/f97ab0872927bcb6a50fce5c8c3c04dbf3391770
