### ISSUE TITLE
ChunkException

### ISSUE THREAD

**Issue by Mcayear** [Mcayear/LittleMonster#3]
```
14:13:00 [ERROR] [LittleMonster] BasePluginThreadTask Error
cn.nukkit.utils.ChunkException: Invalid garbage Chunk given to Entity
        at cn.nukkit.entity.Entity.init(Entity.java:577) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.entity.Entity.<init>(Entity.java:520) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.entity.EntityLiving.<init>(EntityLiving.java:46) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.entity.EntityCreature.<init>(EntityCreature.java:13) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at com.smallaswater.littlemonster.entity.vanilla.ai.entity.MovingVanillaEntity.<init>(MovingVanillaEntity.java:25) ~[?:?]
        at com.smallaswater.littlemonster.entity.vanilla.VanillaOperateNPC.<init>(VanillaOperateNPC.java:92) ~[?:?]
        at com.smallaswater.littlemonster.entity.vanilla.VanillaNPC.<init>(VanillaNPC.java:88) ~[?:?]
        at com.smallaswater.littlemonster.config.MonsterConfig.spawn(MonsterConfig.java:294) ~[?:?]
        at com.smallaswater.littlemonster.threads.runnables.SpawnMonsterTask.scheduler(SpawnMonsterTask.java:55) ~[?:?]
        at com.smallaswater.littlemonster.threads.runnables.BasePluginThreadTask.run(BasePluginThreadTask.java:27) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
```

服务器存在一位玩家

**Comment by Mcayear** [comment]
https://github.com/Mcayear/LittleMonster/commit/e0368796a1e650e966964f05e53ee3dd94aa780a
